### ISSUE TITLE
AUTH0 login issues.

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-assets#291] opened 2020-09-08 16:53 UTC
This has been a common theme with many users having login issues since deployment of AUTH0.

It also seems to have broken parts of the SSO by keeping users logged out of other parts of the site unless they login again in that section.

EG. moving from the forum to the blog which SSO handled before no longer works. That same for other parts of the site in the same manner.

The consternation this causes people has been felt in the forum and beyond as it is no longer a seamless operation to navigate the whole site.

For further reference https://forum.arduino.cc/index.php?topic=703139.0  and https://forum.arduino.cc/index.php?topic=703285.0  Although there are some more posts in the forum.

**Comment by MartinL1** [comment] 2020-09-09 07:23
@BallscrewBob Thanks for raising this issue.

I can confirm that this issue is making the Arduino Forum really difficult to navigate and frustrating to use, as the site is constantly logging me in and out while I browse through the forum pages. This was never a problem in the past.

My tracking blocker was also flagging up cloudflare, trustarc and hotjar. I've disabled the blocker for the Arduino Forum site, but the problem still persists. I'm using Firefox 80.0.1 64-bit.

**Comment by BallscrewBob** [comment] 2020-09-09 17:48
And another from the foreign sections  https://forum.arduino.cc/index.php?topic=704382.new#new

**Comment by BallscrewBob** [comment] 2020-09-10 02:50
Additionally I too am now getting signed OUT mid session within periods as small as 5 minutes.

**Comment by BallscrewBob** [comment] 2020-09-15 15:06
For those with CHROME browsers there are a few extensions out there that will do an AUTO REFRESH to get around a lot of the login issues.  
Not sure if this may be frowned on as it does to some extent negate the actual use of AUTH0.

It is not something we should even have to use to make the forum usable which affects every level of user but for those of us who spend more time in there (lots of us) it certainly makes it more manageable.

Other browsers may also have the ability to circumvent AUTH0 so a google search for "auto refresh" may be what you need to do.

**Comment by BallscrewBob** [comment] 2020-09-15 15:11
@MartinL1 
Cloudflare and trustarc MUST be allowed.
Not found a way around those at this point.

**Comment by MartinL1** [comment] 2020-09-15 17:11
@BallscrewBob 

> Cloudflare and trustarc MUST be allowed.

I'm OK with that and have disabled my tracking blocker for their site. 

The forum continues to randomly sign me in and out move between pages though. I guess it's just a minor inconvenience, but would be nice if could be solved.

**Comment by BallscrewBob** [comment] 2020-09-16 14:22
https://youtu.be/zy1Z_Gq-AjM
 This is a short video of just one of the current issues

**Comment by TLS-Rocketry** [comment] 2020-09-17 08:13
> The forum continues to randomly sign me in and out move between pages though. I guess it's just a minor inconvenience, but would be nice if could be solved.

Yep it would be as even I sometimes face the same issue

**Comment by supernova-ws** [comment] 2020-09-17 09:16
> https://youtu.be/zy1Z_Gq-AjM
That's how arudino.cc intended to work - due to high load and high request count. You can click "sign in" to refresh status on main site. Other sites should login you instantly.

**Comment by MartinL1** [comment] 2020-09-17 10:16
@supernova-ws On the contrary, this is not how the Arduino.cc forum is intended to work. The site effectively logs you out after logging in and then proceeds to log you in and out as you browse between pages.

**Comment by BallscrewBob** [comment] 2020-09-17 13:25
Having to continually log in with such short periods of less than 5 minutes in many instances, and also having to also re-sign in to get to other parts of the same site is currently unacceptable.

Clearly this change from the past system has some severe issues and does nothing to help users navigate the site or the forum in particular. Extra logins are completely unnecessary and the time schedules are completely inadequate to sustain traversing the site or forum.

Some form of mitigation is clearly required if users are not to be forced away by these time-outs.

**Comment by sterretjeToo** [comment] 2020-10-21 14:37
I haven't lost posts for a long time. But I agree with BallscrewBob and MartinL1 that it's ridiculous and frustrating that you have to click sign-in to get your login status refreshed.

**Comment by per1234** [comment] 2023-04-05 10:32
I haven't experienced the specific fault reported here, or seen any recent reports of it from other users so I'm going to close this as resolved. If anyone is still experiencing it, please comment here and I'll investigate.

---

I do see periodic reports of confusion or concern caused by what is almost the opposite behavior, as described here:

https://forum.arduino.cc/t/how-can-i-disable-auto-login/935076

That behavior is still present, but I it is quite distinct from the problem this issue was tracking.

**Closed by per1234** 2023-04-05 10:32 UTC
Labels: type: imperfection, topic: forum software
